name: "Build test release with artifact"

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Release version"
        required: true

jobs:
  create-test-release:
    runs-on: ubuntu-latest

    steps:
      # Cleanup workspace path
      - name: Cleanup workspace path
        uses: mickem/clean-after-action@v1
        
        # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create sample release file
        id: sample
        run: 
          file_name="example-output.dat"
          dd if=/dev/zero of=$file_name  bs=1M  count=24
          echo "::set-output name=file_name::$file_name"

      # Create release and upload asset file
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.release-version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: example/release-note.md
          prerelease: true
          owner: powerIO-GmbH
          artifacts: ${{ steps.sample.outputs.file_name }}