name: "Build test release with artifact"

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Release version"
        required: true

jobs:
  create-test-release:
    runs-on: ubuntu-latest

    steps:
      # Cleanup workspace path
      - name: Cleanup workspace path
        uses: AutoModality/action-clean@v1

        # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create sample release binary file
        id: sample_binary
        run: |
          file_name="example-output.dat"
          dd if=/dev/zero of=$file_name bs=1M count=24
          echo "name=$file_name" >> $GITHUB_OUTPUT

      - name: Download sample release picture file
        id: sample_image
        run: |
          file_name="example-image.jpg"
          wget -O $file_name https://images.unsplash.com/photo-1542553458-79a13aebfda6?ixlib=rb-4.0.3&dl=valentin-wallet-s1Iq2bRoR6Q-unsplash.jpg&q=80&fm=jpg&crop=entropy&cs=tinysrgb
          echo "name=$file_name" >> $GITHUB_OUTPUT

      - name: Create example text file
        id: sample_text
        run: |
          file_name="example-text.txt"
          dd if=/dev/urandom bs=786438 count=1 | base64 > $file_name
          echo "name=$file_name" >> $GITHUB_OUTPUT

      # Create release and upload asset file
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.release-version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: example/release-note.md
          prerelease: false
          owner: KevinRohn
          artifacts: "${{ steps.sample_binary.outputs.name }},${{ steps.sample_image.outputs.name }},${{ steps.sample_text.outputs.name }}"