name: "Example of full release data"

on:
  workflow_dispatch:


jobs:
  get-release-notes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create markdown output file
        id: output_file
        run: |
          output_file_name="release-note.md"
          touch $output_file_name

          echo "notes=$output_file_name" >> $GITHUB_OUTPUT
      
      - name: Get "${{ github.repository }}" Release notes
        id: release_data
        uses: KevinRohn/github-full-release-data@update
        with: 
          body-markdown-file-path: ${{ steps.output_file.outputs.notes }}

      - name: Upload downloaded release-note as Workflow artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.output_file.outputs.notes }}

  download-release-asset:
    runs-on: ubuntu-latest
  
    steps:    
      - name: Download release asset from "${{ github.repository }}"
        id: release_data
        uses: KevinRohn/github-full-release-data@update
        with: 
          asset-file: '*.dat'
          asset-output: './'

      - name: (DEBUG) Show file output
        run: |
          ls -lah
