name: "Example of full release data"

on:
  workflow_dispatch:


jobs:
  get-release-notes:
    runs-on: ubuntu-latest
    
    steps:

      # Cleanup workspace path
      - name: Cleanup workspace path
        uses: mickem/clean-after-action@v1

      - name: Create markdown output file
        id: output_file
        run: |
          output_file_name="release-note.md"
          touch $output_file_name

          echo "::set-output name=notes::$output_file_name"
      
      - name: Get "${{ github.repository }}" Release notes
        id: release_data
        uses: KevinRohn/github-full-release-data@documentation
        with: 
          body-markdown-file-path: ${{ steps.output_file.outputs.notes }}

      - name: Upload downloaded release-note as Workflow artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.output_file.outputs.notes }}

  download-release-asset:
    runs-on: ubuntu-latest
  
    steps:
      # Cleanup workspace path
      - name: Cleanup workspace path
        uses: mickem/clean-after-action@v1
    
      - name: Download release asset from "${{ github.repository }}"
        id: release_data
        uses: KevinRohn/github-full-release-data@documentation
        with: 
          asset-file: '*.dat'
          asset-output: './'

      - name: (DEBUG) Show file output
        run: |
          ls -lah
